routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/getComments/{postCode}', 'InstagramController@index')->name('get.comments');
Route::get('/wait/{postCode}', 'InstagramController@waitPage');
Route::get('/comments/{postCode}', 'InstagramController@getAllComments')->name('read.comments');
Route::get('/comments-post/export/{postId}', 'PostController@export')->name('export.comments');

Route::resource('posts', 'PostController');
// Route::resource('comments', 'CommentController');
Route::resource('accounts', 'AccountController');
Route::resource('errors', 'ErrorController');

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Post extends Model
{
    use SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'instagram_post_code',
        'sleep_time',
        'count',
        'total',
        'max_id',
        'paginateInd'
    ];

    public function comments()
    {
        return $this->hasMany(Comment::class, 'post_id','id');
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use Phpfastcache\Helper\Psr16Adapter;

use App\Account;
use App\Comment;
use App\Post;
use App\Exports\CommentsExport;
use Maatwebsite\Excel\Facades\Excel;
use Illuminate\Support\Facades\Crypt;

class PostController extends Controller
{
    private function accountReset(){
        $accounts = Account::all()->count();
        $in_use = Account::where('in_use', 1)->get()->count();
        if($in_use == $accounts){
            $allAccounts = Account::all();
            foreach($allAccounts as $oneAccount){
                $oneAccount->update(['in_use' => 0]);
            }
        }
    }

    private function decryptHash($hash)
    {
        if (empty($hash)) return [];

        $decrypted = Crypt::decryptString($hash); // array

        $result = explode('..', $decrypted);
        $data = [
            'email'     => $result[0] ?? '',
            'password'  => $result[1] ?? '',
            'date'      => $result[2] ?? ''
        ];

        return $data['password'];
    }

     /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if(isset($request->q) AND $request->q != ""){
            $query = Post::query();        
            $columns = Schema::getColumnListing('posts');
            
            foreach($columns as $column)
            {
                $query->orWhere($column, 'LIKE', '%'.$request->q.'%');
            }

            $posts = $query->orderBy('id','DESC')->paginate();
            return view('post.index',['posts' => $posts]);
        }
        
        $posts = Post::orderBy('id','desc')->paginate();

        foreach ($posts as $post)
            $post->commentsCount = Comment::where('post_id', $post->id)->count();

        return view('post.index',['posts' => $posts]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('post.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request) {
        
        $instagramAccount = Account::where('in_use', 0)->first();
        $instagramAccount->update(['in_use' => 1]);
        $this->accountReset();

        $username = $instagramAccount['email'];
        $password = $this->decryptHash($instagramAccount['password']);
        
        $instagram = \InstagramScraper\Instagram::withCredentials(new \GuzzleHttp\Client(), $username, $password, new Psr16Adapter('Files'));

        $instagram->login(); // will use cached session if you want to force login $instagram->login(true)
        $instagram->saveSession(); //DO NOT forget this in order to save the session, otherwise have no sense

        $response = $instagram->getPaginateMediaCommentsByCode($request->instagram_post_code, 1, null);
        $totalComments = $response->commentsCount;

        Post::create([
            'name'                  => $request->name,
            'instagram_post_code'   => $request->instagram_post_code,
            'sleep_time'            => ($request->sleep_time * 60),
            'count'                 => $request->count,
            'total'                 => $totalComments,
            'max_id'                => $request->max_id,
            'paginateInd'           => $request->paginateInd,
        ]);

        $request->session()->flash('status', 'Post cadastrado com sucesso!');
        return redirect()->to(route('posts.index'));
    }

     /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $post = Post::withTrashed()->findOrFail($id);
        $data = "<table class='table table-bordered table-striped table-hover' width='100%'>";
        $data .= "<tr><td><b>Post</b></td><td>".$post->name."</td></tr>";
        $data .= "<tr><td><b>Code</b></td><td>".$post->instagram_post_code."</td></tr>";
        $data .= "<tr><td><b>Pausa</b></td><td>".$post->sleep_time."</td></tr>";
        $data .= "<tr><td><b>Quantidade</b></td><td>".$post->count."</td></tr>";
        $data .= "<tr><td><b>Maior ID</b></td><td>".$post->total."</td></tr>";
        $data .= "<tr><td><b>Criado</b></td><td>".$post->created_at->format('d/m/Y H:i:s')."</td></tr>";
        $data .= "</table>";

        return $data;
        ;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $post = Post::findOrFail($id);
        return view('post.edit',['post' => $post]);
    }

     /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $instagramAccount = Account::where('in_use', 0)->first();
        $instagramAccount->update(['in_use' => 1]);
        $this->accountReset();

        $username = $instagramAccount['email'];
        $password = $this->decryptHash($instagramAccount['password']);
        
        $instagram = \InstagramScraper\Instagram::withCredentials(new \GuzzleHttp\Client(), $username, $password, new Psr16Adapter('Files'));

        $instagram->login(); // will use cached session if you want to force login $instagram->login(true)
        $instagram->saveSession(); //DO NOT forget this in order to save the session, otherwise have no sense

        $response = $instagram->getPaginateMediaCommentsByCode($request->instagram_post_code, 1, null);
        $totalComments = $response->commentsCount;

        $post = Post::findOrFail($id);
        
        $username = $request->username;
        $password = $request->password;

        $post->update([
            'name'                  => $request->name,
            'instagram_post_code'   => $request->instagram_post_code,
            'sleep_time'            => ($request->sleep_time * 60),
            'count'                 => $request->count,
            'total'                 => $totalComments,
            'max_id'                => $request->max_id,
            'paginateInd'           => $request->paginateInd,
        ]);

        $request->session()->flash('status', 'Post atualizado com sucesso!');
        return redirect()->to(route('posts.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        $comments   = Comment::where('post_id', $id)->delete();
        $post       = Post::findOrFail($id)->delete();

        $request->session()->flash('status', 'Post deletado com sucesso!');
        return redirect()->to(route('posts.index'));
    }

    /**
     * Export Excel CSV
     */
    public function export($postId) 
    {
        // return Excel::download(new CommentsExport($postId), 'users.xlsx');
        return (new CommentsExport($postId))->download('comentarios-'.$postId.'.csv', \Maatwebsite\Excel\Excel::CSV, ['Content-Type' => 'text/csv']);
    }
}

resources/views/post/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header text-center">
                    <i class="fa fa-instagram"></i> Criar Conta
                </div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    <form method="POST" action="{{ route('posts.store') }}">
                        {{ csrf_field() }}
                        <div class="form-group">
                            <label for="name">Nome do Post</label>
                            <input type="text" class="form-control" id="name" name="name"  placeholder="Nome do Post" required>
                        </div> 
                        <div class="form-group">
                            <label for="name">Código do Post</label>
                            <input type="text" class="form-control" id="instagram_post_code" name="instagram_post_code"  placeholder="Código do Post" required>
                        </div> 
                        <div class="form-group">
                            <label for="name">Tempo de espera (Em minutos)</label>
                            <input type="number" class="form-control" id="sleep_time" name="sleep_time"  placeholder="Tempo de Espera" required>
                        </div>
                        <div class="form-group">
                            <label for="name">Quantidade de comentários para puxar</label>
                            <input type="number" class="form-control" id="count" name="count"  placeholder="Quantidade de comentários" required>
                        </div>                     
                        <a href="{{ route('posts.index') }}" class="btn btn-danger pull-left">Voltar</a>                       
                        <button type="submit" class="btn btn-success pull-right">Criar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/post/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header text-center">
                    <i class="fa fa-calendar"></i> Editar Conta
                </div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    <form method="POST" action="{{ route('posts.update', ['post' => $post->id]) }}">
                        {{ csrf_field() }}
                        {{ method_field('PUT') }}
                        <div class="form-group">
                            <label for="name">Nome do Post</label>
                            <input type="text" class="form-control" id="name" name="name"  placeholder="Nome do Post" required value="{{$post->name}}">
                        </div> 
                        <div class="form-group">
                            <label for="name">Código do Post</label>
                            <input type="text" class="form-control" id="instagram_post_code" name="instagram_post_code"  placeholder="Código do Post" required value="{{$post->instagram_post_code}}">
                        </div>
                        <div class="form-group">
                            <label for="name">Tempo de espera (Em minutos)</label>
                            <input type="number" class="form-control" id="sleep_time" name="sleep_time"  placeholder="Nome do Post" required value="{{ ($post->sleep_time/60) }}">
                        </div>
                        <div class="form-group">
                            <label for="name">Quantidade de comentários para puxar</label>
                            <input type="number" class="form-control" id="count" name="count"  placeholder="Nome do Post" required value="{{$post->count}}">
                        </div>                      
                        <a href="{{ route('posts.index') }}" class="btn btn-danger pull-left">Voltar</a>                       
                        <button type="submit" class="btn btn-success pull-right">Editar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/post/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header text-center">
                    <button type="button" class="btn btn-primary btn-sm btn-search pull-left" data-toggle="modal" data-tooltip="tooltip" data-target="#search" data-placement="top" title="Pesquisar">
                        <i class="fa fa-search"></i>
                    </button>
                    <i class="fa fa-calendar"></i> Posts
                    <a href="{{ route('posts.create') }}" class="pull-right btn btn-success btn-sm" data-toggle="tooltip" data-placement="top" title="Adicionar"><i class="fa fa-plus"></i></a>
                </div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success text-center" role="alert">
                            <i class="fa fa-check"></i> {{ session('status') }}
                        </div>
                    @endif

                    <table id="example1" class="table table-bordered table-striped table-hover" width="100%">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Nome</th>
                                <th>Post</th>
                                <th>Espera</th>
                                <th>Puxar Qtd</th>
                                <th>Total / Baixados</th>
                                <th>Comentários</th>
                                <th>Ações</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($posts as $post)
                            <tr>
                                <td class="align-middle">
                                    {{$post->id}}
                                </td>
                                <td class="align-middle">
                                    {{$post->name}}
                                </td>
                                <td class="align-middle">
                                    {{$post->instagram_post_code}}
                                </td>
                                <td class="align-middle">
                                    {{ ($post->sleep_time/60) }}
                                </td>
                                <td class="align-middle">
                                    {{$post->count}}
                                </td>
                                <td class="align-middle">
                                    {{ $post->commentsCount }} / {{$post->total}}
                                </td>
                                <td class="align-middle">
                                    <a href="{{ route('read.comments', ['postCode' => $post->instagram_post_code]) }}" class="btn btn-primary btn-sm" data-toggle="tooltip" data-placement="top" title="Visualizar Comentários">
                                        <i class="fa fa-comments"></i>
                                    </a>
                                    <a href="{{ route('get.comments', ['postCode' => $post->instagram_post_code]) }}" class="btn btn-success btn-sm" data-toggle="tooltip" data-placement="top" title="Puxar Comentários">
                                        <i class="fa fa-download"></i>
                                    </a>
                                    <a href="{{ route('export.comments', ['postId' => $post->id]) }}" class="btn btn-warning btn-sm" data-toggle="tooltip" data-placement="top" title="Criar CSV">
                                    <i class="fa fa-table"></i>
                                    </a>
                                </td>
                                <td class="text-center align-middle">
                                    <div class="row" style="padding:0; margin:0;">
                                        <div class="col-md-4" style="padding:0; margin:0;">
                                            <button type="button" class="btn btn-success btn-sm btn-posts" data-toggle="modal" data-tooltip="tooltip" data-target="#posts" data-placement="top" title="Visualizar" data-id="{{$post->id}}">
                                                <i class="fa fa-eye"></i>
                                            </button>
                                        </div>
                                        <div class="col-md-4" style="padding:0; margin:0;">
                                            <a href="{{ route('posts.edit', ['post' => $post->id]) }}" class="btn btn-primary btn-sm" data-toggle="tooltip" data-placement="top" title="Editar">
                                                <i class="fa fa-pencil"></i>
                                            </a>
                                        </div>
                                        <div class="col-md-4" style="padding:0; margin:0;">
                                            <form method="POST" action="{{ route('posts.destroy', ['post' => $post->id]) }}" style="padding:0; margin:0;">
                                                {{ csrf_field() }}
                                                {{ method_field('DELETE') }}

                                                <div class="form-group" style="padding:0; margin:0;">
                                                    <button type="submit" class="btn btn-danger btn-sm delete-post" data-toggle="tooltip" data-placement="top" title="Deletar"><i class="fa fa-trash"></i></button>
                                                </div>
                                            </form>
                                        </div>
                                    </div>      
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                        
                    </table>
                    {{ $posts->links() }}
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Modal posts -->
<div class="modal fade" id="posts" tabindex="-1" role="dialog" aria-labelledby="postsLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="postsLabel">posto</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <div class="posts"></div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal">Fechar</button>
      </div>
    </div>
  </div>
</div>

<!-- Modal Search -->
<div class="modal fade" id="search" tabindex="-1" role="dialog" aria-labelledby="searchLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-body">
        <form action="posts" type="GET">
            <div class="input-group">
                <input type="text" class="form-control q" placeholder="Digite o que deseja pesquisar..." name="q" required>
                <div class="input-group-btn">
                <button class="btn btn-success" type="submit">
                    <i class="fa fa-search"></i>
                </button>
                </div>
            </div>
        </form>        
      </div>     
    </div>
  </div>
</div>

<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
<script>
    $(document).ready(function(){
        $('#search').on('shown.bs.modal', function() {
            $('input:text:visible:first').focus();
        })

        $(".btn-posts").on('click', function(){
            id = $(this).data('id');
            $.ajax({
                url: 'posts/'+id,
                type: 'GET',
                dataType: 'html',
                success: function (html) {
                    $(".posts").html(html);
                }
            });
        });

        $('.delete-post').click(function(e){
            e.preventDefault() // Don't post the form, unless confirmed
            Swal.fire({
                title: 'Você tem certeza?',
                text: "Não será possível revertar esta ação!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Sim, deletar!'
            }).then((result) => {
                if (result.value) {
                    Swal.fire(
                    'Deletado!',
                    'Dado deletado com sucesso.',
                    'success'
                    );
                    $(e.target).closest('form').submit();
                }
            });
        });
    }); 

    $(function () {
        $('[data-toggle="tooltip"]').tooltip();
        $('[data-tooltip="tooltip"]').tooltip();
    })   
</script>
@endsection